version: "3.7"
services:
  test_server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports: 
      - '4321:5432'

volumes:
  db: